name: CI Checks
on:
  push:
    branches:
      - main
    paths:
      - hello-api/**
      - .github/workflows/**
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    env:
      working-directory: ./hello-api
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug
        run: ls -l
        working-directory: ${{env.working-directory}}
      - name: Run Tests
        run: make test
        working-directory: ${{env.working-directory}}
      - name: Coverage Check
        run: make coverage
        working-directory: ${{env.working-directory}}
      - name: Generate Report
        run: make report
        working-directory: ${{env.working-directory}}
      - name: Copy Files
        run: |
          mkdir reports
          cp cover.html reports/.
        working-directory: ${{env.working-directory}}
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ${{env.working-directory}}/reports

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test
    env:
      working-directory: ./hello-api

    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make build
        working-directory: ${{env.working-directory}}

      - name: Copy Files
        run: |
          mkdir artifacts
          cp api artifacts/.
        working-directory: ${{env.working-directory}}

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{env.working-directory}}/artifacts

  deliver:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: api
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
           In process test
          draft: false
          prerelease: false
      - name: Upload Release binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.upload_url }}
          asset_path: api
          asset_name: api
          asset_content_type: application/octet-stream
