name: CI Checks
on:
  push:
    branches:
      - main
    paths:
      - hello-api/**
      - .github/workflows/**
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    env:
      working-directory: ./hello-api
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Tests
        run: make test
        working-directory: ${{env.working-directory}}
      - name: Coverage Check
        run: make coverage
        working-directory: ${{env.working-directory}}
      - name: Generate Report
        run: make report
        working-directory: ${{env.working-directory}}
      - name: Copy Files
        run: |
          mkdir reports
          cp cover.html reports/.
        working-directory: ${{env.working-directory}}
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ${{env.working-directory}}/reports

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test
    env:
      working-directory: ./hello-api

    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make build
        working-directory: ${{env.working-directory}}

      - name: Copy Files
        run: |
          mkdir artifacts
          cp api artifacts/.
        working-directory: ${{env.working-directory}}

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{env.working-directory}}/artifacts

  deliver:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: api
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            In process test
          draft: true
          prerelease: true
      - name: Upload Release binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: api
          asset_name: api
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/octet-stream
  deploy-function:
    name: Deployo FaaS
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auth for deploy
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: translate
          entry_point: Translate
          runtime: go119
      # - name: Deploy App
      #   id: deploy
      #   uses: google-github-actions/deploy-appengine@v1
      - name: test
        run: curl "{{ steps.deploy.outputs.url }}/hello"
