name: CI Checks
on:
  push:
    branches:
      - main
    paths:
      - hello-api/**
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    env:
      working-directory: ./hello-api

    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make build
        working-directory: ${{env.working-directory}}

      - name: Copy Files
        run: |
          mkdir artifacts
          cp api artifacts/.
        working-directory: ${{env.working-directory}}

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{env.working-directory}}/artifacts
